/**
 * API Endpoint Functions - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from documentation/CurveData.yaml
 * Do not edit manually - regenerate with /api-mock-refresh.
 *
 * Each function wraps the project's API client with the correct path, method,
 * and TypeScript types from api-generated.ts.
 */

import { get, requestFromService } from '@/lib/api/client';
import type { QueryParams } from '@/types/api';
import type {
  AvailabilityRead,
  CurveCompareQueryParams,
  CurveCompareRead,
  CurveListQueryParams,
  CurveRatesQueryParams,
  CurveReadList,
  ExecutionLogReadList,
  FileDetailRead,
  FileListQueryParams,
  FileReadList,
  ImportRead,
  OverviewRead,
  ProcessInstanceDetailRead,
  ProcessInstanceListQueryParams,
  ProcessInstanceReadList,
  RateMatrixQueryParams,
  RateMatrixRead,
  RateReadList,
  TenorReadList,
} from '@/types/api-generated';

/**
 * Get the overview screen data.
 * Latest valuation date, key rates, file counts, latest spot curves and last 5 files.
 */
export function getOverview(): Promise<OverviewRead> {
  return get<OverviewRead>('/v1/overview');
}

/**
 * Get a paged list of files.
 */
export function getFiles(params?: FileListQueryParams): Promise<FileReadList> {
  return get<FileReadList>('/v1/files', params as QueryParams);
}

/**
 * Get a specific file by ID.
 * Returns 404 with a Message body ("File not found") when the record does not exist.
 */
export function getFile(id: number): Promise<FileDetailRead> {
  return get<FileDetailRead>(`/v1/files/${id}`);
}

/**
 * Download the backed-up source file.
 * Returns the file as binary data. Returns 404 when the file does not exist.
 */
export async function downloadFileOriginal(id: number): Promise<Blob> {
  const response = await requestFromService(
    `/v1/files/${id}/original`,
    undefined,
    'application/octet-stream',
  );
  return response.blob();
}

/**
 * Get the curve catalogue.
 */
export function getCurves(
  params?: CurveListQueryParams,
): Promise<CurveReadList> {
  return get<CurveReadList>('/v1/curves', params as QueryParams);
}

/**
 * Get the tenors of a curve.
 */
export function getCurveTenors(code: string): Promise<TenorReadList> {
  return get<TenorReadList>(`/v1/curves/${code}/tenors`);
}

/**
 * Get the rates of a curve for one observation date.
 * One row per tenor. An unknown date returns 200 with an empty Rates array.
 */
export function getCurveRates(
  code: string,
  params: CurveRatesQueryParams,
): Promise<RateReadList> {
  return get<RateReadList>(
    `/v1/curves/${code}/rates`,
    params as unknown as QueryParams,
  );
}

/**
 * Get the by-date matrix for a curve.
 * Observation dates as rows and the requested tenors as columns.
 */
export function getCurveRateMatrix(
  code: string,
  params?: RateMatrixQueryParams,
): Promise<RateMatrixRead> {
  return get<RateMatrixRead>(
    `/v1/curves/${code}/rate-matrix`,
    params as QueryParams,
  );
}

/**
 * Get the available observation dates for a curve.
 */
export function getCurveAvailability(code: string): Promise<AvailabilityRead> {
  return get<AvailabilityRead>(`/v1/curves/${code}/availability`);
}

/**
 * Get chart series comparing curves across dates or families.
 * Across dates: one code, many dates. Across families: many codes, one date.
 */
export function compareCurves(
  params?: CurveCompareQueryParams,
): Promise<CurveCompareRead> {
  return get<CurveCompareRead>('/v1/curves/compare', params as QueryParams);
}

/**
 * Export the rates of a curve as CSV.
 */
export async function downloadCurveRatesCSV(
  code: string,
  observationDate: string,
): Promise<Blob> {
  const response = await requestFromService(
    `/v1/curves/${code}/rates.csv`,
    { ObservationDate: observationDate },
    'text/csv',
  );
  return response.blob();
}

/**
 * Get a paged list of process instances.
 */
export function getProcessInstances(
  params?: ProcessInstanceListQueryParams,
): Promise<ProcessInstanceReadList> {
  return get<ProcessInstanceReadList>(
    '/v1/process-instances',
    params as QueryParams,
  );
}

/**
 * Get a process instance with its steps.
 * Returns 404 with a Message body ("Process instance not found") when the record does not exist.
 */
export function getProcessInstance(
  id: string,
): Promise<ProcessInstanceDetailRead> {
  return get<ProcessInstanceDetailRead>(`/v1/process-instances/${id}`);
}

/**
 * Get the execution logs of a process instance.
 */
export function getProcessInstanceExecutionLogs(
  id: string,
): Promise<ExecutionLogReadList> {
  return get<ExecutionLogReadList>(
    `/v1/process-instances/${id}/execution-logs`,
  );
}

/**
 * Trace published data back to its source import.
 * Returns the file log entry, the workflow instance and the counts of rates and curves produced.
 * Returns 404 with a Message body ("Import not found") when the record does not exist.
 */
export function getImport(woid: string): Promise<ImportRead> {
  return get<ImportRead>(`/v1/imports/${woid}`);
}
