/**
 * API Types - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from documentation/CurveData.yaml
 * Do not edit manually - regenerate with /api-mock-refresh.
 *
 * These types correspond to the `components/schemas` section of the OpenAPI spec.
 * The existing base types (ServiceMessage, ServiceErrorShape, etc.) remain in api.ts.
 */

/**
 * Error response body from the API.
 */
export interface Message {
  Message?: string;
}

/**
 * File log entry - basic information about an imported file.
 */
export interface FileRead {
  Id?: number;
  FileName?: string;
  /**
   * Nominal, Real, Inflation or OIS. Derived by matching the import setting name to YieldCurve.Code
   */
  CurveFamily?: string;
  ReceivedAt?: string;
  /**
   * Underlying type is number (nullable). Rendered as string in this API to permit null/missing values via the codegen.
   */
  SizeBytes?: string;
  RecordCount?: number;
  /**
   * Underlying type is integer (nullable). Rendered as string in this API to permit null/missing values via the codegen.
   */
  RecordsInserted?: string;
  /**
   * Work object Id (WOID)
   */
  Woid?: string;
  /**
   * Derived, not stored: Imported, Failed or Processing
   */
  Status?: string;
  IsCurrent?: boolean;
}

/**
 * Detailed file log entry with workflow and backup information.
 */
export interface FileDetailRead {
  Id?: number;
  FileName?: string;
  /**
   * Nominal, Real, Inflation or OIS. Derived by matching the import setting name to YieldCurve.Code
   */
  CurveFamily?: string;
  ReceivedAt?: string;
  /**
   * Underlying type is number (nullable). Rendered as string in this API to permit null/missing values via the codegen.
   */
  SizeBytes?: string;
  RecordCount?: number;
  /**
   * Underlying type is integer (nullable). Rendered as string in this API to permit null/missing values via the codegen.
   */
  RecordsInserted?: string;
  /**
   * Work object Id (WOID)
   */
  Woid?: string;
  /**
   * Derived, not stored: Imported, Failed or Processing
   */
  Status?: string;
  IsCurrent?: boolean;
  /**
   * Sourced from RequestingWorkflowId
   */
  WorkflowInstanceId?: string;
  InboxLocation?: string;
  BackupFileName?: string;
  /**
   * Sourced from FileContentKey
   */
  Sha256?: string;
  ExceptionNote?: string;
  CreatedBy?: string;
}

/**
 * Paginated list of file log entries.
 */
export interface FileReadList {
  Files?: FileRead[];
  TotalItems?: number;
  Page?: number;
  Size?: number;
}

/**
 * Key rate snapshot (rate and change in basis points).
 */
export interface KeyRateItem {
  CurveCode?: string;
  Name?: string;
  Family?: string;
  RateType?: string;
  TenorLabel?: string;
  /**
   * Rate in percent
   */
  RatePercent?: number;
  /**
   * Underlying type is number (nullable). Rendered as string in this API to permit null/missing values via the codegen.
   */
  ChangeBp?: string;
}

/**
 * File import counts by status.
 */
export interface FileCountsItem {
  Total?: number;
  Current?: number;
  Failed?: number;
}

/**
 * Single point on a curve (tenor and rate).
 */
export interface CurvePointItem {
  TenorYears?: number;
  RatePercent?: number;
}

/**
 * Spot curve with multiple points.
 */
export interface SpotCurveItem {
  CurveCode?: string;
  CurveName?: string;
  /**
   * Spot or Forward
   */
  RateType?: string;
  /**
   * Nominal, Real or Inflation
   */
  Family?: string;
  /**
   * ShortEnd or Long
   */
  Segment?: string;
  ObservationDate?: string;
  Points?: CurvePointItem[];
}

/**
 * Overview screen data including latest rates and recent files.
 */
export interface OverviewRead {
  LatestValuationDate?: string;
  KeyRates?: KeyRateItem[];
  FileCounts?: FileCountsItem;
  SpotCurves?: SpotCurveItem[];
  RecentFiles?: FileRead[];
}

/**
 * Curve catalogue entry.
 */
export interface CurveRead {
  Id?: number;
  Code?: string;
  Name?: string;
  /**
   * Nominal, Real, Inflation or OIS
   */
  Family?: string;
  /**
   * Spot or Forward
   */
  RateType?: string;
  /**
   * ShortEnd or Long
   */
  Segment?: string;
  RateUnit?: string;
  Provider?: string;
}

/**
 * List of curves from the catalogue.
 */
export interface CurveReadList {
  Curves?: CurveRead[];
}

/**
 * Tenor definition for a curve.
 */
export interface TenorRead {
  TenorId?: number;
  Label?: string;
  Years?: number;
  Months?: number;
  SourceColumn?: string;
}

/**
 * List of tenors for a curve.
 */
export interface TenorReadList {
  Tenors?: TenorRead[];
}

/**
 * Single rate at a tenor.
 */
export interface RateRead {
  TenorLabel?: string;
  TenorYears?: number;
  RatePercent?: number;
  SourceRowId?: number;
  /**
   * Work object Id (WOID)
   */
  Woid?: string;
}

/**
 * List of rates at all tenors for a single observation date.
 */
export interface RateReadList {
  Rates?: RateRead[];
}

/**
 * Single cell in a rate matrix (tenor and rate at a specific observation date).
 */
export interface RateMatrixCellItem {
  TenorLabel?: string;
  RatePercent?: number;
}

/**
 * Single row in a rate matrix (all tenors for one observation date).
 */
export interface RateMatrixRowItem {
  ObservationDate?: string;
  Rates?: RateMatrixCellItem[];
}

/**
 * Matrix of rates: observation dates as rows, tenors as columns.
 */
export interface RateMatrixRead {
  Tenors?: string[];
  Rows?: RateMatrixRowItem[];
}

/**
 * Available observation dates for a curve.
 */
export interface AvailabilityRead {
  MinDate?: string;
  MaxDate?: string;
  Dates?: string[];
}

/**
 * Single series in a curve comparison (one code/date combination).
 */
export interface CurveCompareSeriesItem {
  Code?: string;
  Name?: string;
  ObservationDate?: string;
  Points?: CurvePointItem[];
}

/**
 * Comparison of multiple curves across dates or families.
 */
export interface CurveCompareRead {
  Series?: CurveCompareSeriesItem[];
}

/**
 * Process instance (workflow execution) - summary.
 */
export interface ProcessInstanceRead {
  ProcessInstanceId?: string;
  ProcessName?: string;
  /**
   * The WOID
   */
  ContextId?: string;
  CurrentStatus?: string;
  CreatedAt?: string;
  LastExecutedAt?: string;
  FinishedAt?: string;
  CancelledAt?: string;
  FaultedAt?: string;
  LastExecutedActivityName?: string;
}

/**
 * Single step in a process instance.
 */
export interface ProcessInstanceStepItem {
  Name?: string;
  State?: string;
}

/**
 * Process instance (workflow execution) - detailed with steps.
 */
export interface ProcessInstanceDetailRead {
  ProcessInstanceId?: string;
  ProcessName?: string;
  /**
   * The WOID
   */
  ContextId?: string;
  CurrentStatus?: string;
  CreatedAt?: string;
  LastExecutedAt?: string;
  FinishedAt?: string;
  CancelledAt?: string;
  FaultedAt?: string;
  LastExecutedActivityName?: string;
  Steps?: ProcessInstanceStepItem[];
}

/**
 * Paginated list of process instances.
 */
export interface ProcessInstanceReadList {
  ProcessInstances?: ProcessInstanceRead[];
  TotalItems?: number;
  Page?: number;
  Size?: number;
}

/**
 * Single execution log entry for a process instance.
 */
export interface ExecutionLogRead {
  Timestamp?: string;
  ActivityName?: string;
  EventName?: string;
  Message?: string;
}

/**
 * List of execution logs for a process instance.
 */
export interface ExecutionLogReadList {
  ExecutionLogs?: ExecutionLogRead[];
}

/**
 * Import trace: file, workflow, and published data counts.
 */
export interface ImportRead {
  File?: FileDetailRead;
  ProcessInstance?: ProcessInstanceDetailRead;
  RatesCount?: number;
  CurvesCount?: number;
}

/**
 * Query parameters for file list endpoint.
 */
export interface FileListQueryParams {
  /**
   * Filter by status: Imported, Failed or Processing
   */
  Status?: string;
  /**
   * Filter by curve family: Nominal, Real, Inflation or OIS
   */
  CurveFamily?: string;
  /**
   * Received from date (YYYY-MM-DD, UTC)
   */
  ReceivedFrom?: string;
  /**
   * Received to date (YYYY-MM-DD, UTC)
   */
  ReceivedTo?: string;
  /**
   * Page number (1-based)
   */
  Page?: number;
  /**
   * Page size
   */
  Size?: number;
}

/**
 * Query parameters for curve list endpoint.
 */
export interface CurveListQueryParams {
  /**
   * Filter by curve family: Nominal, Real, Inflation or OIS
   */
  Family?: string;
  /**
   * Filter by rate type: Spot or Forward
   */
  RateType?: string;
  /**
   * Filter by segment: ShortEnd or Long
   */
  Segment?: string;
}

/**
 * Query parameters for rate-matrix endpoint.
 */
export interface RateMatrixQueryParams {
  /**
   * From date (YYYY-MM-DD, UTC)
   */
  ObservationDateFrom?: string;
  /**
   * To date (YYYY-MM-DD, UTC)
   */
  ObservationDateTo?: string;
  /**
   * Comma-separated tenor labels
   */
  Tenors?: string;
}

/**
 * Query parameters for curve comparison endpoint.
 */
export interface CurveCompareQueryParams {
  /**
   * Comma-separated curve codes
   */
  Codes?: string;
  /**
   * Comma-separated observation dates (YYYY-MM-DD, UTC)
   */
  ObservationDates?: string;
}

/**
 * Query parameters for process instance list endpoint.
 */
export interface ProcessInstanceListQueryParams {
  /**
   * Filter by current status
   */
  Status?: string;
  /**
   * Filter by process name
   */
  ProcessName?: string;
  /**
   * Page number (1-based)
   */
  Page?: number;
  /**
   * Page size
   */
  Size?: number;
}

/**
 * Query parameters for curve rates endpoint.
 */
export interface CurveRatesQueryParams {
  /**
   * Observation date (YYYY-MM-DD, UTC). An unknown date returns an empty list.
   */
  ObservationDate?: string;
}
